### ISSUE TITLE
Rendering abstracts instead of entire articles

### ISSUE THREAD

**Issue by ThorbenLindhauer** [nikku/kartoffeldruck#1]
On overview pages, I'd like to generate article abstracts (e.g. first paragraph) instead of entire articles. Is there already some way to do this that I am missing?
If not, what do you think about adding some kind of hooks to the generator#generate function?

**Comment by nikku** [comment]
You can use a special helper to generate abstracts for articles. Have a look at [nikku/lefedt.de](https://github.com/nikku/lefedt.de), a website that uses this technique.

What it does is the following:
- [create an excerpt helper](https://github.com/nikku/lefedt.de/blob/master/helpers/excerpt.js)
- [include it as a filter](https://github.com/nikku/lefedt.de/blob/master/kartoffeldruck.js#L24)
- [use the helper, specifying the location of the actual page](https://github.com/nikku/lefedt.de/blob/master/pages/blog/index.html)
