### ISSUE TITLE
ESLint + Git + LF cause massive useless linting errors on Windows

### ISSUE THREAD

**Issue by jrehwaldt** [nikku/kartoffeldruck#10]
Since the eslint integration LF line endings are enforced. This is okay, but requires additional settings from the repository maintainer. Basically, git anyway only checks in LF endings no matter what the user uses. On Windows line endings are usually auto-converted when checked out, which leads to massive linting errors. 

To fix either this constraints has to be removed or the `.gitattributes` altered to enforce LF endings on all files.

Additionally, it'd be nice to have a. `editorconfig` specifying the settings for line ending, LF-at-end-of-file-or-not and trailing spaces.

Fix asap. Thanks!

**Comment by nikku** [comment]
Got your point on git checking in LF anyways. Please check if removing the following line from the `.eslintrc` file fixes the issue:

```
    "linebreak-style": [ 2, "unix" ],
```

**Comment by jrehwaldt** [comment]
Thanks. Had no time to test, but I'll report back if that didn't do the trick (unlikely anyway). Nonetheless, editorconfig is not desired?
