### ISSUE TITLE
Pagination with zero items creates no page at all

### ISSUE THREAD

**Issue by ThorbenLindhauer** [nikku/kartoffeldruck#2]
When generating a list of posts with pagination and the number of items is 0, no page is generated.

I'd expect that the first page is generated nonetheless, even though it contains no items.

The reason is the loop in https://github.com/nikku/kartoffeldruck/blob/master/lib/kartoffeldruck.js#L111 that is not entered when there are no items.

**Comment by ThorbenLindhauer** [comment]
Thanks!

**Comment by nikku** [comment]
Released fix as [v0.2.3](https://github.com/nikku/kartoffeldruck/releases/tag/v0.2.3)

**Comment by nikku** [comment]
You are welcome :grinning:
