### ISSUE TITLE
Emit <generated> event for each change

### ISSUE THREAD

**Issue by jrehwaldt** [nikku/kartoffeldruck#8]
It would be neat to have a callback invoked for each generated page. Signature would probably be `(filename, locals, options)`. Options are optional but would allow to use a single callback function for subsequent generation steps and still react to those. But that's likely anyway bad design and it could therefore be omitted.

**Comment by nikku** [comment]
Any use case for which that could be useful?

**Comment by jrehwaldt** [comment]
No, I just generate issues... :sleeping: Of course, sitemap generation for example.

**Comment by jrehwaldt** [comment]
Sitemap generation can also be opinionated embedded, but implementations might want to alter the modification-date strategy based on their SCM or the like...

**Comment by nikku** [comment]
What about emitting events on the `druck` instance for each generated page? Would that help your use case?

**Comment by jrehwaldt** [comment]
Jo. EventEmitter is also there already -- but in this case I need the `options` passed to `druck.generate`.

**Comment by nikku** [comment]
Please add a PR for this (including test cases).

**Comment by jrehwaldt** [comment]
RSS / Atom feed generation is another very much needed use case for this.
